



 

 
ALL:
	gcc -o multicastClientIpv4 multicastClientIpv4.c
	gcc -o multicastClientIpv6 multicastClientIpv6.c
	gcc -o multicastServerIpv4 multicastServerIpv4.c
	gcc -o multicastServerIpv6 multicastServerIpv6.c

clean:
	rm -rf $(OBJ) multicastClientIpv4  multicastClientIpv6 multicastServerIpv4 multicastServerIpv6

	
.PHONY: clean ALL       

